# Generated by Django 4.1.1 on 2022-09-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('density', models.IntegerField(blank=True, null=True)),
                ('loss_pips', models.FloatField()),
                ('profit_pips', models.FloatField()),
                ('rank', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
    ]
