# Generated by Django 4.1.1 on 2022-09-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
