# Generated by Django 4.1.1 on 2022-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coin_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='leverage',
            field=models.IntegerField(default=20),
        ),
    ]
